import { readFile, writeFile } from 'node:fs/promises'
import { tracks } from './catalog.mjs'
import { publicTrack, stages, promotions } from './shared.mjs'

const quote = value => `'${String(value).replaceAll("'", "''")}'`
const json = JSON.stringify(tracks.map(publicTrack), null, 2) + '\n'
const levels = tracks.flatMap(track => stages.map((stage,i) => `(${quote(track.slug)},${quote(stage.rank)},${quote(stage.title)},${promotions.find(p=>p.rank===stage.rank).xp},${i+1})`)).join(',\n')
const modules = tracks.flatMap(track => track.exercises.map(e=>`(${quote(track.slug)},${quote(e.rank)},${quote(e.slug)},${quote(e.title)},${e.position},${e.xp})`)).join(',\n')
const sql = `-- Generated by content/web/generate.mjs. Edit the source catalog, then regenerate before release.
INSERT INTO learning.skill_levels (skill_id, rank, title, xp_required, sort_order, content_version)
SELECT s.id, v.rank::learning.rank_code, v.title, v.xp, v.position, 'web-v1'
FROM (VALUES
${levels}
) AS v(skill,rank,title,xp,position)
JOIN learning.skills s ON s.slug=v.skill JOIN learning.blocks b ON b.id=s.block_id
JOIN learning.domains d ON d.id=b.domain_id AND d.slug='web';

INSERT INTO learning.learning_modules (skill_level_id, slug, title, kind, sort_order, xp_reward, status, content_ref, content_version)
SELECT l.id, v.slug, v.title, 'EXERCISE', v.position, v.xp, 'PUBLISHED', v.slug, 'web-v1'
FROM (VALUES
${modules}
) AS v(skill,rank,slug,title,position,xp)
JOIN learning.skills s ON s.slug=v.skill JOIN learning.blocks b ON b.id=s.block_id
JOIN learning.domains d ON d.id=b.domain_id AND d.slug='web'
JOIN learning.skill_levels l ON l.skill_id=s.id AND l.rank=v.rank::learning.rank_code;

INSERT INTO learning.exercises (module_id, language, entrypoint, test_bundle_ref, time_limit_ms, memory_limit_mb)
SELECT m.id, s.slug, CASE WHEN s.slug='html' THEN 'index.html' ELSE 'styles.css' END,
 'content/web/' || s.slug || '.mjs#' || m.slug, 8000, 256
FROM learning.learning_modules m JOIN learning.skill_levels l ON l.id=m.skill_level_id
JOIN learning.skills s ON s.id=l.skill_id
WHERE m.content_version='web-v1' AND s.slug IN ('html','css');
`
for (const [path, content] of [['../../backend/internal/learning/web_catalog.json', json], ['../../database/migrations/0005_web_exercises.sql', sql]]) {
  const url = new URL(path, import.meta.url)
  if (process.argv.includes('--check')) {
    if (await readFile(url,'utf8') !== content) throw new Error(`Generated artifact out of date: ${path}`)
  } else await writeFile(url, content, 'utf8')
}
