-- Generated by content/web/generate.mjs. Edit the source catalog, then regenerate before release.
INSERT INTO learning.skill_levels (skill_id, rank, title, xp_required, sort_order, content_version)
SELECT s.id, v.rank::learning.rank_code, v.title, v.xp, v.position, 'web-v1'
FROM (VALUES
('html','E','Premiers pas',0,1),
('html','D','Fondamentaux',150,2),
('html','C','Autonomie',600,3),
('html','B','Cas complexes',1600,4),
('html','A','Composition experte',3900,5),
('html','S','Épreuves de maîtrise',18900,6),
('css','E','Premiers pas',0,1),
('css','D','Fondamentaux',150,2),
('css','C','Autonomie',600,3),
('css','B','Cas complexes',1600,4),
('css','A','Composition experte',3900,5),
('css','S','Épreuves de maîtrise',18900,6)
) AS v(skill,rank,title,xp,position)
JOIN learning.skills s ON s.slug=v.skill JOIN learning.blocks b ON b.id=s.block_id
JOIN learning.domains d ON d.id=b.domain_id AND d.slug='web';

INSERT INTO learning.learning_modules (skill_level_id, slug, title, kind, sort_order, xp_reward, status, content_ref, content_version)
SELECT l.id, v.slug, v.title, 'EXERCISE', v.position, v.xp, 'PUBLISHED', v.slug, 'web-v1'
FROM (VALUES
('html','E','html-01','Hello World',1,20),
('html','E','html-02','Titre et introduction',2,30),
('html','E','html-03','Une liste de matériel',3,40),
('html','E','html-04','Un sommaire navigable',4,60),
('html','D','html-05','Une image documentée',5,75),
('html','D','html-06','Les repères d’une page',6,100),
('html','D','html-07','Un tableau lisible',7,125),
('html','D','html-08','Un premier formulaire',8,150),
('html','C','html-09','Des données sémantiques',9,180),
('html','C','html-10','Un choix exclusif',10,220),
('html','C','html-11','Une FAQ native',11,260),
('html','C','html-12','Un vrai document',12,340),
('html','B','html-13','Des en-têtes croisés',13,400),
('html','B','html-14','Images adaptatives',14,500),
('html','B','html-15','Contrôles hors formulaire',15,600),
('html','B','html-16','Écritures et langues',16,800),
('html','A','html-17','Une édition scientifique',17,900),
('html','A','html-18','Média et alternatives',18,1100),
('html','A','html-19','Un modèle inerte',19,1300),
('html','A','html-20','Une réservation native',20,1700),
('html','S','html-21','S · Matrice à trois axes',21,1800),
('html','S','html-22','S · Contrat de soumission',22,2200),
('html','S','html-23','S · Document international',23,2600),
('html','S','html-24','S · Dossier de synthèse',24,3400),
('css','E','css-01','Une première couleur',1,20),
('css','E','css-02','Une hiérarchie typographique',2,30),
('css','E','css-03','Mesurer une boîte',3,40),
('css','E','css-04','Cibler sans déborder',4,60),
('css','D','css-05','Une barre flexible',5,75),
('css','D','css-06','Une grille régulière',6,100),
('css','D','css-07','Un rythme vertical',7,125),
('css','D','css-08','États d’un bouton',8,150),
('css','C','css-09','Une grille responsive',9,180),
('css','C','css-10','Un thème avec variables',10,220),
('css','C','css-11','Défilement local',11,260),
('css','C','css-12','Un badge sans HTML supplémentaire',12,340),
('css','B','css-13','Une interface bidirectionnelle',13,400),
('css','B','css-14','Réagir au conteneur',14,500),
('css','B','css-15','Maîtriser la cascade',15,600),
('css','B','css-16','Respecter le mouvement réduit',16,800),
('css','A','css-17','Alignement par sous-grille',17,900),
('css','A','css-18','Dimensionnement intrinsèque',18,1100),
('css','A','css-19','Un état piloté par le formulaire',19,1300),
('css','A','css-20','Une édition imprimable',20,1700),
('css','S','css-21','S · Composant réutilisable',21,1800),
('css','S','css-22','S · Architecture de cascade',22,2200),
('css','S','css-23','S · Plusieurs modes de lecture',23,2600),
('css','S','css-24','S · Interface sous contraintes',24,3400)
) AS v(skill,rank,slug,title,position,xp)
JOIN learning.skills s ON s.slug=v.skill JOIN learning.blocks b ON b.id=s.block_id
JOIN learning.domains d ON d.id=b.domain_id AND d.slug='web'
JOIN learning.skill_levels l ON l.skill_id=s.id AND l.rank=v.rank::learning.rank_code;

INSERT INTO learning.exercises (module_id, language, entrypoint, test_bundle_ref, time_limit_ms, memory_limit_mb)
SELECT m.id, s.slug, CASE WHEN s.slug='html' THEN 'index.html' ELSE 'styles.css' END,
 'content/web/' || s.slug || '.mjs#' || m.slug, 8000, 256
FROM learning.learning_modules m JOIN learning.skill_levels l ON l.id=m.skill_level_id
JOIN learning.skills s ON s.id=l.skill_id
WHERE m.content_version='web-v1' AND s.slug IN ('html','css');
